server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 159621
  data:
    redis:
      host: 192.168.235.129
      port: 6379
      password: 159621
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  #===========RabbitMQ=============
  rabbitmq:
    host: 192.168.235.129
    port: 5672
    virtual-host: /hmdp
    username: hmdp
    password: 123
    connection-timeout: 1s #MQ连接超时时间
    template:
      retry:
        enabled: true #开启超时重试机制
        initial-interval: 1000ms #失败后的初始等待时间
        multiplier: 1 #失败后下次的等待时长倍数
        max-attempts: 3 #最大重试次数
#  data:
#    redis:
#      lettuce:
#        pool:
#          max-active:
#          max-idle:
#          min-idle:
#          time-between-eviction-runs:
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

